### ISSUE TITLE
Does not work for SVGElements in IE10

### ISSUE THREAD

**Issue by benjaminmcdonald** [eligrey/classList.js#13]

**Comment by PatAtMacadamian** [comment]
Fixed in my fork. 
https://github.com/PatAtMacadamian/classList.js
Added a pull request, so hopefully it will be added to the main project shortly.

**Comment by jdanyow** [comment]
@PatAtMacadamian :+1:

**Comment by extempl** [comment]
@PatAtMacadamian :+1:

**Comment by eligrey** [comment]
Fixed in #40
