### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by KayLeung** [eligrey/classList.js#35]
Sorry for any inconvenience this may have caused. Because of #33, could you tag a release again?

@see #22, #32.

Thanks

**Comment by ruijse** [comment]
@eligrey just to clarify, in #32 you tagged a release, but as per #33 the minified version of the file is 6 months older than the actual file. Just wondering if you could please tag a new release to fix this? Thanks!

**Comment by eligrey** [comment]
https://github.com/eligrey/classList.js/releases/tag/2014-12-13
