### ISSUE TITLE
Add package.json ...

### ISSUE THREAD

**Issue by binarykitchen** [eligrey/classList.js#41]
... for npm, thanks!

**Comment by binarykitchen** [comment]
hello??

**Comment by eligrey** [comment]
You are permitted to redistribute classList.js on any package managers. The MIT license allows to do pretty much anything. All of the information required for the package.json npm metadata can be found in the source if you want to upload classList.js to npm.

**Comment by binarykitchen** [comment]
Right, couldn't wait any longer and already did that:
https://github.com/binarykitchen/cross-class-list
https://www.npmjs.com/package/cross-class-list

But now we have duplicate code which is bad in my view ...
