### ISSUE TITLE
DOMException is undefined in IE8

### ISSUE THREAD

**Issue by axelboc** [eligrey/classList.js#49]
Line 50 throws a `DOMException is undefined` error in IE8:

```
this.code = DOMException[type];
```

Has nobody ever encountered this error before!? It seems that `DOMException` is indeed not supported at all on IE8:
- http://www.webbrowsercompatibility.com/dom/desktop/ https://msdn.microsoft.com/en-us/library/ff974354
- https://msdn.microsoft.com/en-us/library/ff974354

**Comment by eligrey** [comment]
Luckily, functionally an error is still going to be thrown, but for the wrong reasons. Thanks for bringing this up, and I'll patch it tomorrow (if I don't please remind me)

**Comment by tschallacka** [comment]
*cough* has this been patched?
tomorrow is saturday :-P

**Comment by eligrey** [comment]
@tschallacka I'm very busy with my commercial work atm, but I will eventually get to this. If you cannot wait, I will review any pull requests you have.
