### ISSUE TITLE
tag the repo?

### ISSUE THREAD

**Issue by jay8t6** [eligrey/classList.js#61]
Can you tag the latest commit please? using semantic versioning maybe? v1.0.0 or something like that..

**Comment by eligrey** [comment]
The version of the latest commit is [1.1.20170112](https://github.com/eligrey/classList.js/blob/41da0b1ce6a2eedc4489097fc22b2c6848556da9/classList.js#L3).

**Comment by jay8t6** [comment]
thanks!

**Comment by jay8t6** [comment]
@eligrey i still dont see it, maybe its not pushed?

**Comment by eligrey** [comment]
@jay8t6 here's a tag https://github.com/eligrey/classList.js/releases/tag/1.1.20170112
