### ISSUE TITLE
Maintenance Woes

### ISSUE THREAD

**Issue by beck** [eligrey/classList.js#63]
@eligrey what are your plans for this project?

There has been some grumbling about the lack of attention.

We have [forked and published](https://github.com/yola/classlist-polyfill) this repo but package management is a mess.

Would you be amendable to transferring this project to an organization, https://github.com/yola, and letting an engineering team manage it?

If nothing else, add a few collaborators, including:

* @beck
* @stefanor (fellow coworker)
* @stevenvachon 
* @tbranyen (if willing?)

@tbranyen if ☝️  happens, could you add some collaborators to:
* https://www.npmjs.com/package/classlist.js

Including:
* https://www.npmjs.com/~yola
* https://www.npmjs.com/~beck

I would very much like to shut-down our fork and work from a single source of truth.

**Comment by stevenvachon** [comment]
@beck you're ignoring me.

**Comment by beck** [comment]
Updated.

**Comment by stevenvachon** [comment]
I'll be the negative ninny and say that I don't expect to hear a single word from @eligrey for at least 6 months.

**Comment by tbranyen** [comment]
So long as your fork maintains the same API, I'm alright with having ya'll start pushing releases to the npm package namespace. To be fair to @eligrey, let's give him some time to respond first. He may give ya'll merge rights to this repo (he should IMO), and then I'll add you all to the NPM package and you should be able to get it back into a good spot.

**Comment by eligrey** [comment]
Sorry everyone. I have a lot of stuff going on in my personal life and at OFTN Inc. I've been too busy to adequately maintain this repository.

I am giving @tbranyen and @beck full access to this repo and full control over the direction.

@tbranyen and @beck please don't merge @stevenvachon's pull requests that large multiple unrelated changes all at once, or at least if you do they must be very well documented. I had one look at #53 and it was very off-putting.

**Comment by tbranyen** [comment]
@eligrey no worries, I'm not particularly happy with his attitude in general around this project. As a maintainer and someone also going through personal stuff I understand. Thanks for your help, it's in good hands :-p

**Comment by stevenvachon** [comment]
Do whatever you want. My code makes projects better.

**Comment by tbranyen** [comment]
@stevenvachon I'm sure it does, but your attitude does nothing of the sort.

**Comment by stevenvachon** [comment]
@tbranyen and waiting 2 years for a response does?

**Comment by tbranyen** [comment]
@beck What state is your fork in right now? Is it in a place where you could open a PR? Once we get this repo in good shape, we can publish the next artifact (IMO a major bump) to NPM.

**Comment by beck** [comment]
The fork is near identical. The only difference is that it has a solution for https://github.com/eligrey/classList.js/issues/48.

I've opened a [Roadmap issue](https://github.com/eligrey/classList.js/issues/64), a better place to talk about "what's next?" instead of this issue. Feel free to edit and disagree with it. No hard opinions there.

Thanks @eligrey for letting others pitch in.
