### ISSUE TITLE
The contains method have inverted condition

### ISSUE THREAD

**Issue by strayiker** [eligrey/classList.js#75]
```
classListProto.contains = function (token) {
	return !~checkTokenAndGetIndex(this, token + "");
};
```
~x operator are equal -(x+1)
for **x=-1**
```
!~(-1)
!-(-1+1)
!-0
!0
true
```
so, if checkTokenAndGetIndex() did not found token in array (**return -1**), then contains() method will return **true**

**Comment by englishextra** [comment]
@strayiker are you talking about this version https://github.com/eligrey/classList.js/blob/1.2.201711092/classList.js

**Comment by strayiker** [comment]
Yes
