### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by sfw2327** [eligrey/classList.js#82]
Hello -

I asked Doug Beck if you could add a permissive license, such as an MIT license to his classlist library.  He pointed me in your direction.  Would you be willing to add a permissive license, such as an MIT license to this repo?  My company will not let me use the repo with the unlicense. 

Thanks, 

Stevi

**Comment by eligrey** [comment]
You can do anything you want with the permissions granted to you by the unlicense public domain dedication.

You can literally fork my code and change the license to MIT (or completely delete the license) without asking. That's how permissive the current license is.

Feel free to fork the repo and change the license to MIT.

**Comment by sfw2327** [comment]
Thanks for the info.  We unfortunately are unable to fork the code.  Would you consider adding an MIT license?   I can't use the unlicense - this blog post explains why: https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense.

Would appreciate your help on this as we would like to use this library.

**Comment by eligrey** [comment]
You are permitted by my public domain dedication to change or add any license to a fork of this project. In order to fork the project, just click on the fork button.

I'll add an explicit MIT backup license sometime.
